server:
  port: 18080
spring:
  application:
    name: ben-boot
  profiles:
    active: dev

# MyBatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: nben.**.entity
  global-config:
    banner: false
    db-config:
      id-type: AUTO # 自增 ID
      logic-delete-field: isDeleted




