### 查询
GET http://localhost:18080/system/menus
Accept: application/json

### MyMenus
GET http://localhost:18080/system/menus/myMenus
Accept: application/json

### 新增
POST http://localhost:18080/system/menus
Content-Type: application/json

{
  "parentId": "6",
  "menuName": "菜单管理",
  "path": "menu",
  "component": "/system/menu/index",
  "redirect": "",
  "icon": "bx:bx-home",
  "remark": "666"
}

### 修改
PUT http://localhost:18080/system/menus
Content-Type: application/json

{
  "menuId": "3",
  "parentId": "2",
  "menuName": "Analysis",
  "path": "analysis",
  "component": "/dashboard/analysis/index",
  "redirect": "",
  "icon": "bx:bx-home"
}


### 删除
DELETE http://localhost:18080/system/menus
Content-Type: application/json

[
  "2"
]

