### 查询
GET http://localhost:18080/userDepts?userId=1&deptId=2
Accept: application/json

### 新增
POST http://localhost:18080/userDepts
Content-Type: application/json

{
  "userId": "1",
  "deptId": "2"
}
