### 查询
GET http://localhost:18080/userRoles?userId=1&roleId=1
Accept: application/json

### 新增
POST http://localhost:18080/userRoles
Content-Type: application/json

{
  "userId": "1",
  "roleId": "2"
}
